import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@repo/theme';
import { TIRCProvider } from '@repo/tirc';
// Mock config for TIRC

const tircConfig = {
	server: process.env.NEXT_PUBLIC_TWITCH_SERVER || '',
	oauthToken: process.env.NEXT_PUBLIC_TWITCH_OAUTH_TOKEN || '',
	clientId: process.env.NEXT_PUBLIC_TWITCH_CLIENT_ID || '',
	nick: process.env.NEXT_PUBLIC_TWITCH_USERNAME || 'justinfan12345',
	channels: [`#codingbutter`],
};

console.log(tircConfig);
const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ThemeProvider>
			<TIRCProvider config={tircConfig}>
				<html lang="en">
					<body className={`${geistSans.variable} ${geistMono.variable}`}>
						{children}
					</body>
				</html>
			</TIRCProvider>
		</ThemeProvider>
	);
}
